security:
    
    role_hierarchy:
        ROLE_USUARIO:     ROLE_USUARIO
        ROLE_OPERADOR:    ROLE_OPERADOR
        ROLE_GERENTE:     ROLE_GERENTE
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USUARIO, ROLE_OPERADOR, ROLE_GERENTE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'role_user' ] }
        #        admin: { password: adminpass, roles: [ 'role_admin' ] }
        
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /admin/login
                provider: fos_userbundle
            logout:
                path:   /admin/logout
                target: /
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/secured/admin, roles: ROLE_ADMIN }
        #- { path: ^/menu/new, roles: [ROLE_OPERADOR, ROLE_GERENTE, ROLE_ADMIN] }
        #- { path: ^/menu, roles: [ROLE_USUARIO, ROLE_OPERADOR, ROLE_GERENTE, ROLE_ADMIN] }
        #- { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
