INCESComedorBundle_homepage:
    pattern:  /
    defaults: { _controller: INCESComedorBundle:Default:index }

INCESComedorBundle_menu:
    resource: "@INCESComedorBundle/Resources/config/routing/menu.yml"
    prefix:   /menu
