parameters:
#    inces_comedor.example.class: INCES\ComedorBundle\Example

services:
#    inces_comedor.example:
#        class: %inces_comedor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
