usuario:
    pattern:  /
    defaults: { _controller: "INCESComedorBundle:Usuario:index" }

usuario_show:
    pattern:  /{id}/show
    defaults: { _controller: "INCESComedorBundle:Usuario:show" }

usuario_new:
    pattern:  /new
    defaults: { _controller: "INCESComedorBundle:Usuario:new" }

usuario_create:
    pattern:  /create
    defaults: { _controller: "INCESComedorBundle:Usuario:create" }
    requirements: { _method: post }

usuario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "INCESComedorBundle:Usuario:edit" }

usuario_update:
    pattern:  /{id}/update
    defaults: { _controller: "INCESComedorBundle:Usuario:update" }
    requirements: { _method: post }

usuario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "INCESComedorBundle:Usuario:delete" }
    requirements: { _method: post }

usuario_search:
    pattern:  /search
    defaults: { _controller: "INCESComedorBundle:Usuario:search" }
    requirements: { _method: get|post }

usuario_search_ajax:
    pattern:  /searcha
    defaults: { _controller: "INCESComedorBundle:Usuario:searchAjax" }
    requirements: { _method: get|post }

usuario_search_ajax_facturar:
    pattern:  /searchafact
    defaults: { _controller: "INCESComedorBundle:Usuario:searchAjaxFacturar" }
    requirements: { _method: get|post }

usuario_show_facturar:
    pattern:  /{id}/showfacturar
    defaults: { _controller: "INCESComedorBundle:Usuario:showFacturar" }
