# src/INCES/ComedorBundle/Resources/config/doctrine/Menu.orm.yml
INCES\ComedorBundle\Entity\Menu:
   type: entity
   table: Menu
   id:
     id:
        type: integer
        generator: { strategy: AUTO }
   fields:
     seco:
        type: string
        length: 255
     sopa:
        type: string
        length: 255
     dia:
        type: datetime
   oneToMany:
    usuario_menus:
      targetEntity: UsuarioMenu
      mappedBy: menu
