# src/INCES/ComedorBundle/Resources/config/doctrine/UserAdmin.orm.yml
INCES\ComedorBundle\Entity\UserAdmin:
   type: entity
   table: UserAdmin
   id:
     id:
        type: integer
        generator: { strategy: AUTO }
   fields:
        nombre:
            type: string
            length: 255
        apellido:
            type: string
            length: 255
        cedula:
            type: string
            length: 9
        ncarnet:
            type: string
            length: 9
